name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install  
    - run: sudo apt-get -yqq install chromium-chromedriver
    - run: npm install chromedriver --chromedriver-force-download
    - run: sudo apt install chromium-chromedriver
    - run: npm install karma-detect-browsers --save-dev
    - run: npm install karma-firefox-launcher --save-dev
    - run: npm ci
    - run: npm run build 
    - run: npm run test-ci
