name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencias    
    - run: npm install  
    - name: Install drivers
      run: sudo apt-get -yqq install chromium-chromedriver
           npm install chromedriver --chromedriver-force-download
           sudo apt install chromium-chromedriver
           npm install karma-detect-browsers --save-dev
           npm install karma-firefox-launcher --save-dev
      
    - name: Build
      run: npm ci
           npm run build 
    - name: Test 
      run: npm run test-ci
